apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: fleet
  name: routingservice-ingress
  annotations:
    # kubernetes.io/ingress.class: "nginx"
    kubernetes.io/ingress.class: "traefik"
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/enable-opentracing: "true"
    # config: jaeger-collector-host: http://jaeger-collector-service.monitoring.svc.cluster.local:14268/api/traces
    traefik.ingress.kubernetes.io/router.entrypoints: web
status:
  loadBalancer: {}
spec:
  # tls:
  #   - hosts:
  #       - andidroid.io
  #       - localhost
  #     secretName: ingress-tls
  # TODO ingressClassName ???
  # ingressClassName: traefik-lb
  rules:
    - host: andidroid.io
      http:
        paths:
          - path: /fleet/?(.*)
            pathType: Prefix
            backend:
              service:
                name: routingservice-service
                port:
                  number: 80
# ---
# apiVersion: networking.k8s.io/v1
# kind: IngressClass
# metadata:
#   name: traefik-lb
# spec:
#   controller: traefik.io/ingress-controller
